/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ClientesDashboardRouteImport } from './routes/clientes.dashboard'
import { Route as AuthenticatedSaquesRouteImport } from './routes/_authenticated/saques'
import { Route as AuthenticatedParceirosRouteImport } from './routes/_authenticated/parceiros'
import { Route as AuthenticatedParceiroRouteImport } from './routes/_authenticated/parceiro'
import { Route as AuthenticatedEncurtadorRouteImport } from './routes/_authenticated/encurtador'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedAssinantesRouteImport } from './routes/_authenticated/assinantes'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicWebhooksAsgardRouteImport } from './routes/api/public/webhooks.asgard'
import { Route as ApiPublicHooksSendExpiryRemindersRouteImport } from './routes/api/public/hooks/send-expiry-reminders'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesDashboardRoute = ClientesDashboardRouteImport.update({
  id: '/clientes/dashboard',
  path: '/clientes/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSaquesRoute = AuthenticatedSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParceirosRoute = AuthenticatedParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParceiroRoute = AuthenticatedParceiroRouteImport.update({
  id: '/parceiro',
  path: '/parceiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEncurtadorRoute = AuthenticatedEncurtadorRouteImport.update({
  id: '/encurtador',
  path: '/encurtador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinantesRoute = AuthenticatedAssinantesRouteImport.update({
  id: '/assinantes',
  path: '/assinantes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksAsgardRoute = ApiPublicWebhooksAsgardRouteImport.update({
  id: '/api/public/webhooks/asgard',
  path: '/api/public/webhooks/asgard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendExpiryRemindersRoute =
  ApiPublicHooksSendExpiryRemindersRouteImport.update({
    id: '/api/public/hooks/send-expiry-reminders',
    path: '/api/public/hooks/send-expiry-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assinantes': typeof AuthenticatedAssinantesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/encurtador': typeof AuthenticatedEncurtadorRoute
  '/parceiro': typeof AuthenticatedParceiroRoute
  '/parceiros': typeof AuthenticatedParceirosRoute
  '/saques': typeof AuthenticatedSaquesRoute
  '/clientes/dashboard': typeof ClientesDashboardRoute
  '/r/$slug': typeof RSlugRoute
  '/clientes/': typeof ClientesIndexRoute
  '/api/public/hooks/send-expiry-reminders': typeof ApiPublicHooksSendExpiryRemindersRoute
  '/api/public/webhooks/asgard': typeof ApiPublicWebhooksAsgardRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assinantes': typeof AuthenticatedAssinantesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/encurtador': typeof AuthenticatedEncurtadorRoute
  '/parceiro': typeof AuthenticatedParceiroRoute
  '/parceiros': typeof AuthenticatedParceirosRoute
  '/saques': typeof AuthenticatedSaquesRoute
  '/clientes/dashboard': typeof ClientesDashboardRoute
  '/r/$slug': typeof RSlugRoute
  '/clientes': typeof ClientesIndexRoute
  '/api/public/hooks/send-expiry-reminders': typeof ApiPublicHooksSendExpiryRemindersRoute
  '/api/public/webhooks/asgard': typeof ApiPublicWebhooksAsgardRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/assinantes': typeof AuthenticatedAssinantesRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/encurtador': typeof AuthenticatedEncurtadorRoute
  '/_authenticated/parceiro': typeof AuthenticatedParceiroRoute
  '/_authenticated/parceiros': typeof AuthenticatedParceirosRoute
  '/_authenticated/saques': typeof AuthenticatedSaquesRoute
  '/clientes/dashboard': typeof ClientesDashboardRoute
  '/r/$slug': typeof RSlugRoute
  '/clientes/': typeof ClientesIndexRoute
  '/api/public/hooks/send-expiry-reminders': typeof ApiPublicHooksSendExpiryRemindersRoute
  '/api/public/webhooks/asgard': typeof ApiPublicWebhooksAsgardRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/reset-password'
    | '/assinantes'
    | '/comissoes'
    | '/encurtador'
    | '/parceiro'
    | '/parceiros'
    | '/saques'
    | '/clientes/dashboard'
    | '/r/$slug'
    | '/clientes/'
    | '/api/public/hooks/send-expiry-reminders'
    | '/api/public/webhooks/asgard'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/reset-password'
    | '/assinantes'
    | '/comissoes'
    | '/encurtador'
    | '/parceiro'
    | '/parceiros'
    | '/saques'
    | '/clientes/dashboard'
    | '/r/$slug'
    | '/clientes'
    | '/api/public/hooks/send-expiry-reminders'
    | '/api/public/webhooks/asgard'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/reset-password'
    | '/_authenticated/assinantes'
    | '/_authenticated/comissoes'
    | '/_authenticated/encurtador'
    | '/_authenticated/parceiro'
    | '/_authenticated/parceiros'
    | '/_authenticated/saques'
    | '/clientes/dashboard'
    | '/r/$slug'
    | '/clientes/'
    | '/api/public/hooks/send-expiry-reminders'
    | '/api/public/webhooks/asgard'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ClientesDashboardRoute: typeof ClientesDashboardRoute
  RSlugRoute: typeof RSlugRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ApiPublicHooksSendExpiryRemindersRoute: typeof ApiPublicHooksSendExpiryRemindersRoute
  ApiPublicWebhooksAsgardRoute: typeof ApiPublicWebhooksAsgardRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/dashboard': {
      id: '/clientes/dashboard'
      path: '/clientes/dashboard'
      fullPath: '/clientes/dashboard'
      preLoaderRoute: typeof ClientesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saques': {
      id: '/_authenticated/saques'
      path: '/saques'
      fullPath: '/saques'
      preLoaderRoute: typeof AuthenticatedSaquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros': {
      id: '/_authenticated/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof AuthenticatedParceirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiro': {
      id: '/_authenticated/parceiro'
      path: '/parceiro'
      fullPath: '/parceiro'
      preLoaderRoute: typeof AuthenticatedParceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encurtador': {
      id: '/_authenticated/encurtador'
      path: '/encurtador'
      fullPath: '/encurtador'
      preLoaderRoute: typeof AuthenticatedEncurtadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinantes': {
      id: '/_authenticated/assinantes'
      path: '/assinantes'
      fullPath: '/assinantes'
      preLoaderRoute: typeof AuthenticatedAssinantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/asgard': {
      id: '/api/public/webhooks/asgard'
      path: '/api/public/webhooks/asgard'
      fullPath: '/api/public/webhooks/asgard'
      preLoaderRoute: typeof ApiPublicWebhooksAsgardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-expiry-reminders': {
      id: '/api/public/hooks/send-expiry-reminders'
      path: '/api/public/hooks/send-expiry-reminders'
      fullPath: '/api/public/hooks/send-expiry-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendExpiryRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssinantesRoute: typeof AuthenticatedAssinantesRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedEncurtadorRoute: typeof AuthenticatedEncurtadorRoute
  AuthenticatedParceiroRoute: typeof AuthenticatedParceiroRoute
  AuthenticatedParceirosRoute: typeof AuthenticatedParceirosRoute
  AuthenticatedSaquesRoute: typeof AuthenticatedSaquesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssinantesRoute: AuthenticatedAssinantesRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedEncurtadorRoute: AuthenticatedEncurtadorRoute,
  AuthenticatedParceiroRoute: AuthenticatedParceiroRoute,
  AuthenticatedParceirosRoute: AuthenticatedParceirosRoute,
  AuthenticatedSaquesRoute: AuthenticatedSaquesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ClientesDashboardRoute: ClientesDashboardRoute,
  RSlugRoute: RSlugRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ApiPublicHooksSendExpiryRemindersRoute:
    ApiPublicHooksSendExpiryRemindersRoute,
  ApiPublicWebhooksAsgardRoute: ApiPublicWebhooksAsgardRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
